version: '3'
services:
  travelthon:
    image: reachhubcorp/travelthon:latest
    container_name: travelthon
    build:
        context: ./context/
    environment:
        KAFKA_IP: 192.168.0.31
        KAFKA_PORT: 8092
        GEOTROUVETHON_IP: 192.168.0.31
        GEOTROUVETHON_PORT: 9966
        TOPIC_IN: travelthon_in
        TOPIC_OUT: travelthon_out