version: '3'
services:
  travelthon:
    image: reachhubcorp/travelthon:latest
    container_name: travelthon
    build:
        context: ./context/
    environment:
        KAFKA_IP: kafka-ip
        KAFKA_PORT: 8092
        GEOTROUVETHON_IP: geotrouvethon-ip
        GEOTROUVETHON_PORT: 9966
        TOPIC_IN: housToTravel
        TOPIC_OUT: locToColissi
        DEBUG_LEVEL: INFO
