version: '3'
services:
  travelthon:
    image: reachhubcorp/travelthon:latest
    container_name: travelthon
    build:
        context: ./context/
    environment:
        KAFKA_IP: 192.168.0.13
        KAFKA_PORT: 8092
        GEOTROUVETHON_IP: 192.168.0.13
        GEOTROUVETHON_PORT: 9966
        TRAVELTHON_IN: travelthon_in
        TRAVELTHON_OUT: travelthon_out